import vtk
import numpy as np
from vtkmodules.vtkCommonMath import vtkMatrix4x4
from vtkmodules.vtkCommonTransforms import vtkTransform
from vtkmodules.vtkRenderingCore import (vtkActor,vtkAssembly,vtkProp3D)
from vtkmodules.vtkRenderingAnnotation import vtkAxesActor
from vtkmodules.vtkInteractionWidgets import vtkSliderWidget,vtkSliderRepresentation2D
from vtkmodules.vtkRenderingCore import vtkCoordinate
from vtkmodules.vtkCommonCore import vtkCommand

style = vtk.vtkInteractorStyleTrackballCamera()
stlfilename = 'assets/'
f = 1
renwin = vtk.vtkRenderWindow()
ren = vtk.vtkRenderer()
renwin.AddRenderer(ren)
iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renwin)
iren.SetInteractorStyle(style)
base = vtk.vtkAssembly()
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'base_motor_holder_so101_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.SetOrientation(90,0,0)
actor.SetPosition(0.0206915 ,0.0221255 ,0.0300817)
base.AddPart(actor)

axes = vtkAxesActor()
ren.AddActor(axes)

reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'base_so101_v2.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.SetOrientation(90,0,0)
actor.SetPosition(0.0207909, 0.0221255, 0.0300817)
base.AddPart(actor)

reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'sts3215_03a_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)

actor.SetOrientation(0,0,-90)
actor.SetPosition(0.0207909 ,-0.0105745 ,0.0761817)
base.AddPart(actor)

reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'waveshare_mounting_plate_so101_v2.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.SetOrientation(90,0,0)
actor.SetPosition(0.0205915 ,0.0467435, 0.0798817)
base.AddPart(actor)
ren.AddActor(base)


shoulder = vtk.vtkAssembly()
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'sts3215_03a_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateY(90)
actor.RotateX(90)
actor.SetPosition(-0.0303992 ,0.000422241 ,-0.0417)

shoulder.AddPart(actor)
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'motor_holder_so101_base_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateY(-90)
actor.RotateX(90)
actor.SetPosition(-0.0675992 ,-0.000177759, 0.0158499)
shoulder.AddPart(actor)
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'rotation_pitch_so101_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateX(-90)
actor.SetPosition(0.0122008, 2.22413e-05 ,0.0464)
shoulder.AddPart(actor)
shoulder.RotateZ(90)
shoulder.RotateX(-180)
shoulder.SetPosition(0.0207909, -0.0230745, 0.0948817)




upper_arm = vtk.vtkAssembly()
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'sts3215_03a_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateZ(-90)
actor.RotateX(-180)
actor.SetPosition(-0.11257,-0.0155,0.0187)
upper_arm.AddPart(actor)
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'upper_arm_so101_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateX(180)
actor.SetPosition(-0.065085, 0.012 ,0.0182)
upper_arm.AddPart(actor)

transform = vtk.vtkTransform()
transform.Translate(0.0207909, -0.0230745, 0.0948817)
transform.RotateZ(90)
transform.RotateX(-180)
transform.Translate(-0.0303992, -0.0182778, -0.0542)
transform.RotateY(-90)
transform.RotateX(-90)
upper_arm.SetUserMatrix(transform.GetMatrix())




lower_arm = vtk.vtkAssembly()
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'under_arm_so101_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateX(-180)
actor.SetPosition(-0.0648499 ,-0.032, 0.0182)
lower_arm.AddPart(actor)
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'motor_holder_so101_wrist_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateX(-180)
actor.SetPosition(-0.0648499, -0.032 ,0.018)
lower_arm.AddPart(actor)
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'sts3215_03a_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateZ(-180)
actor.RotateX(-180)
actor.SetPosition(-0.1224 ,0.0052 ,0.0187)
lower_arm.AddPart(actor)

transform = vtk.vtkTransform()
transform.Translate(0.0207909, -0.0230745, 0.0948817)
transform.RotateZ(90)
transform.RotateX(-180)
transform.Translate(-0.0303992, -0.0182778, -0.0542)
transform.RotateY(-90)
transform.RotateX(-90)
transform.Translate(-0.11257, -0.028, 2.46331e-16)
transform.RotateZ(90)
lower_arm.SetUserMatrix(transform.GetMatrix())

wrist = vtk.vtkAssembly()
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'sts3215_03a_no_horn_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateY(90)
actor.RotateX(90)
actor.SetPosition(5.55112e-17 ,-0.0424 ,0.0306)
wrist.AddPart(actor)
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'wrist_roll_pitch_so101_v2.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateY(-90)
actor.RotateX(-90)
actor.SetPosition(0, -0.028 ,0.0181)
wrist.AddPart(actor)

transform = vtk.vtkTransform()
transform.Translate(0.0207909, -0.0230745, 0.0948817)
transform.RotateZ(90)
transform.RotateX(-180)
transform.Translate(-0.0303992, -0.0182778, -0.0542)
transform.RotateY(-90)
transform.RotateX(-90)
transform.Translate(-0.11257, -0.028, 2.46331e-16)
transform.RotateZ(90)
transform.Translate(-0.1349, 0.0052 ,1.65232e-16)
transform.RotateZ(-90)
wrist.SetUserMatrix(transform.GetMatrix())

gripper = vtk.vtkAssembly()
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'sts3215_03a_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateX(90)
actor.SetPosition(0.0077, 0.0001, -0.0234)
gripper.AddPart(actor)
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'wrist_roll_follower_so101_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.RotateX(-180)
actor.SetPosition(5.55112e-17, -0.000218214, 0.000949706)
gripper.AddPart(actor)
# ren.AddActor(gripper)



transform = vtk.vtkTransform()
transform.Translate(0.0207909, -0.0230745, 0.0948817)
transform.RotateZ(90)
transform.RotateX(-180)
transform.Translate(-0.0303992, -0.0182778, -0.0542)
transform.RotateY(-90)
transform.RotateX(-90)
transform.Translate(-0.11257, -0.028, 2.46331e-16)
transform.RotateZ(90)
transform.Translate(-0.1349, 0.0052 ,1.65232e-16)
transform.RotateZ(-90)
transform.Translate(0, -0.0611, 0.0181)
transform.RotateZ(180)
transform.RotateX(90)
gripper.SetUserMatrix(transform.GetMatrix())


jaw = vtk.vtkAssembly()
reader = vtk.vtkSTLReader()
reader.SetFileName(stlfilename+'moving_jaw_so101_v1.stl')
reader.Update()
mapper = vtk.vtkPolyDataMapper();
mapper.SetInputData(reader.GetOutput())
actor = vtk.vtkActor()
actor.SetMapper(mapper)
actor.SetPosition(-5.55112e-17, -1.94746e-17, 0.0189)
jaw.AddPart(actor)

transform = vtk.vtkTransform()
transform.Translate(0.0207909, -0.0230745, 0.0948817)
transform.RotateZ(90)
transform.RotateX(-180)
transform.Translate(-0.0303992, -0.0182778, -0.0542)
transform.RotateY(-90)
transform.RotateX(-90)
transform.Translate(-0.11257, -0.028, 2.46331e-16)
transform.RotateZ(90)
transform.Translate(-0.1349, 0.0052 ,1.65232e-16)
transform.RotateZ(-90)
transform.Translate(0, -0.0611, 0.0181)
transform.RotateZ(180)
transform.RotateX(90)
transform.Translate(0.0202 ,0.0188 ,-0.0234)
transform.RotateX(90)
jaw.SetUserMatrix(transform.GetMatrix())

b = np.zeros((4,4))
gripper.GetMatrix().DeepCopy(b.ravel(),gripper.GetMatrix())
gripper_assembly = vtk.vtkAssembly()
gripper_assembly.AddPart(jaw)
gripper_assembly.AddPart(gripper)
gripper_assembly.SetOrigin(b[0][3],b[1][3],b[2][3])

wrist.GetMatrix().DeepCopy(b.ravel(),wrist.GetMatrix())
wrist_assembly = vtk.vtkAssembly()
wrist_assembly.AddPart(gripper_assembly)
wrist_assembly.AddPart(wrist)
wrist_assembly.SetOrigin(b[0][3],b[1][3],b[2][3])

lower_arm.GetMatrix().DeepCopy(b.ravel(),lower_arm.GetMatrix())
lower_arm_assembly = vtk.vtkAssembly()
lower_arm_assembly.AddPart(wrist_assembly)
lower_arm_assembly.AddPart(lower_arm)
lower_arm_assembly.SetOrigin(b[0][3],b[1][3],b[2][3])

upper_arm.GetMatrix().DeepCopy(b.ravel(),upper_arm.GetMatrix())
upper_arm_assembly = vtk.vtkAssembly()
upper_arm_assembly.AddPart(lower_arm_assembly)
upper_arm_assembly.AddPart(upper_arm)
upper_arm_assembly.SetOrigin(b[0][3],b[1][3],b[2][3])

shoulder.GetMatrix().DeepCopy(b.ravel(),shoulder.GetMatrix())
shoulder_arm_assembly = vtk.vtkAssembly()
shoulder_arm_assembly.AddPart(upper_arm_assembly)
shoulder_arm_assembly.AddPart(shoulder)
shoulder_arm_assembly.SetOrigin(b[0][3],b[1][3],b[2][3])
ren.AddActor(shoulder_arm_assembly)


represent = vtkSliderRepresentation2D()
represent.SetMinimumValue(-180)
represent.SetMaximumValue(180)
represent.SetValue(0)
represent.SetTitleText('关节1')
Coordinate = vtkCoordinate()
Coordinate = represent.GetPoint1Coordinate()
Coordinate.SetCoordinateSystemToDisplay()
Coordinate.SetValue(20,50)
Coordinate = vtkCoordinate()
Coordinate = represent.GetPoint2Coordinate()
Coordinate.SetCoordinateSystemToDisplay()
Coordinate.SetValue(200,50)

slider = vtkSliderWidget()
slider.SetRepresentation(represent)
slider.SetInteractor(iren)
slider.On()

def callback(obj,event):
    V = represent.GetValue()
    print(V)
    shoulder_arm_assembly.SetOrientation(0,0,V)

slider.AddObserver(vtkCommand.InteractionEvent,callback)

represent1 = vtkSliderRepresentation2D()
represent1.SetMinimumValue(-180)
represent1.SetMaximumValue(180)
represent1.SetValue(0)
represent1.SetTitleText('关节2')
Coordinate1 = vtkCoordinate()
Coordinate1 = represent1.GetPoint1Coordinate()
Coordinate1.SetCoordinateSystemToDisplay()
Coordinate1.SetValue(20,100)
Coordinate1 = vtkCoordinate()
Coordinate1 = represent1.GetPoint2Coordinate()
Coordinate1.SetCoordinateSystemToDisplay()
Coordinate1.SetValue(200,100)

slider1 = vtkSliderWidget()
slider1.SetRepresentation(represent1)
slider1.SetInteractor(iren)
slider1.On()
def callback1(obj,event):
    V = represent1.GetValue()
    print(V)
    upper_arm_assembly.SetOrientation(V,0,0)

slider1.AddObserver(vtkCommand.InteractionEvent,callback1)


represent2 = vtkSliderRepresentation2D()
represent2.SetMinimumValue(-180)
represent2.SetMaximumValue(180)
represent2.SetValue(0)
represent2.SetTitleText('关节3')
Coordinate2 = vtkCoordinate()
Coordinate2 = represent2.GetPoint1Coordinate()
Coordinate2.SetCoordinateSystemToDisplay()
Coordinate2.SetValue(20,150)
Coordinate2 = vtkCoordinate()
Coordinate2 = represent2.GetPoint2Coordinate()
Coordinate2.SetCoordinateSystemToDisplay()
Coordinate2.SetValue(200,150)

slider2 = vtkSliderWidget()
slider2.SetRepresentation(represent2)
slider2.SetInteractor(iren)
slider2.On()
def callback2(obj,event):
    V = represent2.GetValue()
    print(V)
    lower_arm_assembly.SetOrientation(V,0,0)

slider2.AddObserver(vtkCommand.InteractionEvent,callback2)

represent3 = vtkSliderRepresentation2D()
represent3.SetMinimumValue(-180)
represent3.SetMaximumValue(180)
represent3.SetValue(0)
represent3.SetTitleText('关节4')
Coordinate3 = vtkCoordinate()
Coordinate3 = represent3.GetPoint1Coordinate()
Coordinate3.SetCoordinateSystemToDisplay()
Coordinate3.SetValue(20,200)
Coordinate3 = vtkCoordinate()
Coordinate3 = represent3.GetPoint2Coordinate()
Coordinate3.SetCoordinateSystemToDisplay()
Coordinate3.SetValue(200,200)

slider3 = vtkSliderWidget()
slider3.SetRepresentation(represent3)
slider3.SetInteractor(iren)
slider3.On()
def callback3(obj,event):
    V = represent3.GetValue()
    print(V)
    wrist_assembly.SetOrientation(V, 0, 0)

slider3.AddObserver(vtkCommand.InteractionEvent,callback3)



represent4 = vtkSliderRepresentation2D()
represent4.SetMinimumValue(-180)
represent4.SetMaximumValue(180)
represent4.SetValue(0)
represent4.SetTitleText('关节5')
Coordinate4 = vtkCoordinate()
Coordinate4 = represent4.GetPoint1Coordinate()
Coordinate4.SetCoordinateSystemToDisplay()
Coordinate4.SetValue(20,250)
Coordinate4 = vtkCoordinate()
Coordinate4 = represent4.GetPoint2Coordinate()
Coordinate4.SetCoordinateSystemToDisplay()
Coordinate4.SetValue(200,250)

slider4 = vtkSliderWidget()
slider4.SetRepresentation(represent4)
slider4.SetInteractor(iren)
slider4.On()
def callback4(obj,event):
    V = represent4.GetValue()
    print(V)
    gripper_assembly.SetOrientation(0,V,0)

slider4.AddObserver(vtkCommand.InteractionEvent,callback4)


represent5 = vtkSliderRepresentation2D()
represent5.SetMinimumValue(-180)
represent5.SetMaximumValue(180)
represent5.SetValue(0)
represent5.SetTitleText('关节6')
Coordinate5 = vtkCoordinate()
Coordinate5 = represent5.GetPoint1Coordinate()
Coordinate5.SetCoordinateSystemToDisplay()
Coordinate5.SetValue(20,300)
Coordinate5 = vtkCoordinate()
Coordinate5 = represent5.GetPoint2Coordinate()
Coordinate5.SetCoordinateSystemToDisplay()
Coordinate5.SetValue(200,300)

slider5 = vtkSliderWidget()
slider5.SetRepresentation(represent5)
slider5.SetInteractor(iren)
slider5.On()
def callback5(obj,event):
    V = represent5.GetValue()
    print(V)
    jaw.SetOrientation(0,0,V)

slider5.AddObserver(vtkCommand.InteractionEvent,callback5)

renwin.Render()
iren.Initialize()
iren.Start()

